const assert = require('assert/strict');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const scope = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../content/estate-tactics.js'),'utf8'),scope);
const T = scope.window.CASTLE_ESTATE_TACTICS;
function game(segment=4){const g={W:1280,GY:590,p:{gold:1000,hp:2200,x:0,w:160},e:{gold:1000,hp:2200,x:1120,w:160},estate:{segment},stats:{kills:0,losses:0,unitsSpawned:0,goldEarned:0}};T.init(g);return g;}
function tick(g,seconds,dt=1/60){for(let t=0;t<seconds-1e-8;t+=dt)T.tick(g,Math.min(dt,seconds-t),(base,n)=>{base.hp=Math.max(0,base.hp-n);if(!base.hp)g.over=true;});}
function spawn(g,id,p,x){g.estate.tactics[p?'p':'e']=0;assert(T.recruit(g,id,p));const u=g.estate.units.at(-1);if(x!==undefined)u.x=x;return u;}
let checks=0;
function check(name,fn){fn();checks++;console.log('OK Estate tactics: '+name);}
check('unlock stages, shared funds, separate recruitment cooldown',()=>{const g=game(0);assert.equal(T.status(g,'bike',true).reason,'locked');assert.equal(T.status(g,'neighbor',true).reason,'locked');spawn(g,'dres',true);assert.equal(g.p.gold,982);assert.equal(g.stats.unitsSpawned,1);assert.equal(T.status(g,'dres',true).reason,'recruit');tick(g,2.5);assert(T.status(g,'dres',true).ok);g.p.gold=0;assert.equal(T.status(g,'dres',true).reason,'gold');});
check('every unit reaches the enemy base, hits once, then leaves',()=>{for(const c of T.cards)for(const p of [true,false]){const g=game(c.unlock);spawn(g,c.id,p);tick(g,40);assert.equal((p?g.e:g.p).hp,2200-c.siege);assert.equal(g.estate.units.length,0);assert.equal(g.stats.kills+g.stats.losses,0);}});
check('dres stops bikes; bikes catch exposed neighbours; neighbours kite dres through slowing',()=>{for(const [a,b] of [['dres','bike'],['bike','neighbor'],['neighbor','dres']]){const g=game();spawn(g,a,true,.35);spawn(g,b,false,.65);tick(g,20);assert.equal(g.stats.kills,1,a+' should win');assert.equal(g.stats.losses,0,a+' should survive');}});
check('ranged telegraph, projectile impact and slowdown are real',()=>{const g=game();spawn(g,'neighbor',true,.4);const v=spawn(g,'dres',false,.53);tick(g,.3);assert(g.estate.units[0].wind>0);assert.equal(v.hp,v.max);tick(g,.25);assert.equal(g.estate.shots.length,1);tick(g,.4);assert(v.hp<v.max);assert(v.slow>0);});
check('bins halve ranged damage; night reduces range',()=>{function sample(seg){const g=game(4);spawn(g,'neighbor',true,.38);const v=spawn(g,'dres',false,.52);g.estate.segment=seg;v.wind=100;tick(g,.9);return v.max-v.hp;}assert(sample(4)>0);assert(Math.abs(sample(5)*2-sample(4))<1e-8);assert.equal(sample(7),0);});
check('centre capture rewards control, contested centre resets progress',()=>{const g=game(1);const u=spawn(g,'dres',true,.45);u.wind=100;tick(g,5.1);assert.equal(g.p.gold,988);const v=spawn(g,'dres',false,.55);v.wind=100;tick(g,6);assert.equal(g.p.gold,988);assert.equal(g.estate.tactics.owner,null);});
check('snack zone heals both sides; squad healing cannot resurrect',()=>{const g=game(3),u=spawn(g,'dres',true,.45),v=spawn(g,'dres',false,.55);u.wind=v.wind=100;u.hp=v.hp=50;tick(g,2);assert(Math.abs(u.hp-60)<.01&&Math.abs(v.hp-60)<.01);T.heal(g,true,25);assert(Math.abs(u.hp-85)<.01);u.hp=0;T.heal(g,true,25);assert.equal(u.hp,0);});
check('kebab recruitment, patrol pause/resume and finale siege',()=>{const g=game(8);spawn(g,'bat',true);assert.equal(g.estate.tactics.p,1.2);g.estate.segment=9;g.estate.tactics.clock=11;const x=g.estate.units[0].x;tick(g,2);assert.equal(g.estate.units[0].x,x);tick(g,2);assert(g.estate.units[0].x>x);const f=game(11);spawn(f,'skater',true,.8);tick(f,1);assert.equal(f.e.hp,2200-Math.round(230*1.35));});
check('AI counters visible troops, obeys locks and pays normally',()=>{const g=game();spawn(g,'bike',true);assert.equal(T.choose(g),'dres');g.estate.units=[];spawn(g,'dres',true);assert.equal(T.choose(g),'neighbor');g.estate.segment=0;assert.equal(T.choose(g),'dres');g.e.gold=0;assert.equal(T.choose(g),null);});
check('frame-rate independent combat and bounded effects in a long battle',()=>{function battle(dt){const g=game();for(let i=0;i<8;i++){spawn(g,T.cards[i%3].id,true,.2-i*.025);spawn(g,T.cards[(i+1)%3].id,false,.8+i*.025);}tick(g,60,dt);assert(g.estate.shots.length<10);assert(g.estate.units.every(u=>Number.isFinite(u.x)&&Number.isFinite(u.hp)));return JSON.stringify([g.p.hp,g.e.hp,g.stats,g.estate.units.map(u=>[u.kind,Math.round(u.hp),Math.round(u.x*1000)])]);}assert.equal(battle(1/30),battle(1/120));});
check('recruitment has no hard army cap and game-over blocks purchases',()=>{const g=game();g.p.gold=9999;for(let i=0;i<30;i++)spawn(g,'dres',true);assert.equal(g.estate.units.length,30);g.over=true;assert.equal(T.recruit(g,'dres',false),false);});
check('frontline can pass its own stationary ranged support',()=>{for(const p of [true,false]){const g=game(),support=spawn(g,'neighbor',p,p?.4:.6),front=spawn(g,'dres',p,p?.34:.66),enemy=spawn(g,'dres',!p,p?.54:.46);support.lane=front.lane=enemy.lane=1;enemy.hp=enemy.max=10000;tick(g,4);assert((front.x-support.x)*(p?1:-1)>.02,'melee must overtake support');}});
check('three lanes distribute a crowd without overlapping spawns or limiting purchases',()=>{const g=game();for(let i=0;i<30;i++)spawn(g,'dres',true);for(let lane=0;lane<3;lane++){const row=g.estate.units.filter(u=>u.lane===lane).sort((a,b)=>a.x-b.x);assert.equal(row.length,10);for(let i=1;i<row.length;i++)assert(row[i].x-row[i-1].x>=.043-1e-8);}});
check('equal dres crowds resolve rather than forming a permanent queue',()=>{for(const stage of [0,3,8,9]){const g=game(stage);g.p.hp=g.e.hp=100000;for(let i=0;i<12;i++){spawn(g,T.roster(stage)[0],true);spawn(g,T.roster(stage)[0],false);}tick(g,110);assert(g.stats.kills+g.stats.losses>=12,'combat must resolve at stage '+stage);assert.equal(g.estate.units.filter(u=>u.hp>0).length,0,'no permanent crowd at stage '+stage);}});
check('defeated residents walk home, cannot block, attack or be healed',()=>{const g=game(),u=spawn(g,'bike',true,.45),v=spawn(g,'dres',false,.49);u.hp=1;tick(g,1);assert(u.retreat&&u.hp===0);const x=u.x,hp=v.hp;tick(g,1);assert(u.x<x);assert.equal(v.hp,hp);T.heal(g,true,999);assert.equal(u.hp,0);tick(g,10);assert(!g.estate.units.includes(u));});
check('end of feud clears projectiles and sends squads home without new losses',()=>{const g=game();spawn(g,'dres',true,.5);spawn(g,'neighbor',false,.6);g.estate.shots.push({});const stats=JSON.stringify(g.stats);for(let i=0;i<100;i++)T.finish(g,.1);assert.equal(g.estate.shots.length,0);assert.equal(g.estate.units.length,0);assert.equal(JSON.stringify(g.stats),stats);});
check('six roles form progressive decks; old recruits stay after their card retires',()=>{assert.equal(T.cards.length,6);for(let stage=0;stage<12;stage++){const ids=Array.from(T.roster(stage));assert(ids.length<=4);const g=game(stage);for(const c of T.cards)assert.equal(T.status(g,c.id,true).ok,ids.includes(c.id));}const g=game(4),u=spawn(g,'dres',true);g.estate.segment=5;assert(!T.status(g,'dres',true).ok);tick(g,1);assert(u.hp>0&&u.x>.19);});
console.log('ESTATE TACTICS COMPLETE: '+checks+' checks');
check('bat swing affects a second nearby rival but not a distant one',()=>{const g=game(5);spawn(g,'bat',true,.45);const a=spawn(g,'bike',false,.48),b=spawn(g,'bike',false,.49),far=spawn(g,'bike',false,.7);a.wind=b.wind=far.wind=100;tick(g,.8);assert(a.hp<a.max&&b.hp<b.max);assert.equal(far.hp,far.max);});
check('skater keeps most speed when slowed',()=>{const g=game(7),u=spawn(g,'skater',true,.2);u.slow=3;tick(g,1);assert(u.x>.27);});
check('caretaker restores nearby allies, not enemies or withdrawn units, and auras do not stack',()=>{const g=game(9),a=spawn(g,'bat',true,.4),b=spawn(g,'bat',false,.45),c=spawn(g,'caretaker',true,.35),d=spawn(g,'caretaker',true,.36);[a,b,c,d].forEach(u=>u.wind=100);a.hp=b.hp=50;tick(g,2);assert(Math.abs(a.hp-58)<.001);assert.equal(b.hp,50);a.hp=0;tick(g,.5);assert.equal(a.hp,0);});
